using Npgsql;

namespace TodoApp.Api.Shared;

public static class Database
{
    public const string ConnectionStringEnvironmentVariable = "TODO_DB_CONNECTION";

    public const string DefaultConnectionString =
        "Host=localhost;Port=5432;Database=todoapp;Username=todoapp;Password=todoapp";

    public static string ResolveConnectionString(string? configuredConnectionString)
    {
        return string.IsNullOrWhiteSpace(configuredConnectionString)
            ? DefaultConnectionString
            : configuredConnectionString.Trim();
    }

    public static async Task EnsureCreatedAsync(
        NpgsqlDataSource dataSource,
        CancellationToken cancellationToken = default)
    {
        await using var command = dataSource.CreateCommand("""
            CREATE TABLE IF NOT EXISTS tasks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL CHECK (btrim(title) <> ''),
                is_complete BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            );
            """);

        await command.ExecuteNonQueryAsync(cancellationToken);
    }
}
